# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.68.0"

default_platform :ios

platform :ios do
  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    increment_build_number # version bump
    # match(type: "appstore") # more information: https://codesigning.guide
    gym # Build your app - more options available
    pilot(
      skip_submission: true,
      skip_waiting_for_build_processing: true
      )
    upload_symbols_to_crashlytics
    clean_build_artifacts
  end

  desc "Deploy a new version to the App Store"
  lane :store do
    # match(type: "appstore")
    # snapshot
    gym(
        scheme: "SJ Transit",
        configuration: "Release"
    ) # Build your app - more options available
    upload_symbols_to_crashlytics
    deliver(force: true)
    clean_build_artifacts
    # frameit
  end

  error do |lane, exception|
    puts "Error executing #{lane} - #{exception.message}"
  end
end



# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
